##################################################################################################
# UI service
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-service
        version: "1.0"
        serving: "true"
    spec:
      containers:
        - name: ui-service
          image: sbishyr/starwars-ui:1.0
          imagePullPolicy: Always
          env:
            - name: QUOTE_SERVICE_URL
              value: http://quote-service:8081
            - name: DEATH_STAR_SERVICE_URL
              value: http://death-star-service:8082
          ports:
            - containerPort: 3000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ui-service
    serving: "true"
    version: "1.0"
---